# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctxlog < Formula
  desc "Lightweight CLI tool for persistent, sharded context logging across AI agent sessions"
  homepage "https://github.com/dudarevnikita/ctxlog"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dudarevnikita/ctxlog/releases/download/v0.2.3/ctxlog_0.2.3_darwin_amd64.tar.gz"
      sha256 "e426c890cbc79504a2ec617ad823ce0f2b0f9d572bc77618620297cad929581b"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dudarevnikita/ctxlog/releases/download/v0.2.3/ctxlog_0.2.3_darwin_arm64.tar.gz"
      sha256 "c5be803ea22c3c9446d808dc33c251d2bed1b7b519532affdad93d5e5227d1e8"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarevnikita/ctxlog/releases/download/v0.2.3/ctxlog_0.2.3_linux_amd64.tar.gz"
      sha256 "c9bffdad82f9c9dfffe972d2d9056c22a9288796b3923f4db23106161ee32f99"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarevnikita/ctxlog/releases/download/v0.2.3/ctxlog_0.2.3_linux_arm64.tar.gz"
      sha256 "abe9e8ea2ee0ad7168b0cce52b00b36b526d3e3020c77c99f19eaa2767502ff0"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  test do
    assert_match "usage:", shell_output("#{bin}/ctxlog 2>&1", 1)
  end
end
