# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctxlog < Formula
  desc "Lightweight CLI tool for persistent, sharded context logging across AI agent sessions"
  homepage "https://github.com/dudarievmykyta/ctxlog"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.2/ctxlog_0.3.2_darwin_amd64.tar.gz"
      sha256 "66f3bd798b977b6be4edde1c8e275d8101bff19cb23ecdf18017538e93fbd117"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.2/ctxlog_0.3.2_darwin_arm64.tar.gz"
      sha256 "574ca2b653ab6c8779066a06d100cd2ab22991dd10b052c516de60aff29f65c6"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.2/ctxlog_0.3.2_linux_amd64.tar.gz"
      sha256 "5e496835e6a5f2c2920e01e4b4888ca8848ecdc0b54079c98c830046c518c382"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.2/ctxlog_0.3.2_linux_arm64.tar.gz"
      sha256 "17416a3528fddf6ece5854450f50dc5e264116ae653be9e2043dc59853c363f8"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  test do
    assert_match "Usage:", shell_output("#{bin}/ctxlog 2>&1", 1)
  end
end
