# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctxlog < Formula
  desc "Lightweight CLI tool for persistent, sharded context logging across AI agent sessions"
  homepage "https://github.com/dudarievmykyta/ctxlog"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.1/ctxlog_0.3.1_darwin_amd64.tar.gz"
      sha256 "de705c400cba90263ed487ca06e697cce5b99414690b8bdfefe38bca251f2d9b"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.1/ctxlog_0.3.1_darwin_arm64.tar.gz"
      sha256 "12c5dc9f73caaf6a84457f3a08245d6caddf413f10101c00d071d85faddbfd5f"

      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.1/ctxlog_0.3.1_linux_amd64.tar.gz"
      sha256 "98196461a62548712ee0ad196fea6960b6adc39ba777c76684db361d7fd2c30e"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dudarievmykyta/ctxlog/releases/download/v0.3.1/ctxlog_0.3.1_linux_arm64.tar.gz"
      sha256 "bfce523c0584d0bd87468b3a60ad6390000313afa98d67fc672909e69adced8a"
      define_method(:install) do
        bin.install "ctxlog"
      end
    end
  end

  test do
    assert_match "usage:", shell_output("#{bin}/ctxlog 2>&1", 1)
  end
end
